(deftheme panda
  "Created 2016-11-15.")

(custom-theme-set-faces
 'panda
 '(default ((t (:family "Monaco" :foundry "nil" :width normal :height 161 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#C2C2C2" :background "#161616" :stipple nil :inherit nil))))
 '(cursor ((t (:foreground "#F6F6F6" :background "#F9F9F9"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:font "-outline-Arial-normal-normal-normal-sans-*-*-*-*-p-*-iso8859-1")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#F6F6F6"))))
 '(minibuffer-prompt ((t (:foreground "#F6F6F6"))))
 '(highlight ((t (:background "#161616"))))
 '(region ((t (:foreground "#0E0E0E" :background "#C2C2C2"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#161616"))))
 '(trailing-whitespace ((t (:background "#616161"))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "#F6F6F6"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#9D9D9D"))))
 '(font-lock-comment-face ((t (:weight bold :foreground "#616161"))))
 '(font-lock-constant-face ((t (:weight bold :foreground "#F0F0F0"))))
 '(font-lock-doc-face ((t (:foreground "#616161"))))
 '(font-lock-function-name-face ((t (:foreground "#F0F0F0"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#F6F6F6"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#F6F6F6"))))
 '(font-lock-preprocessor-face ((t (:foreground "#E8E8E8"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#C2C2C2"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#F6F6F6"))))
 '(font-lock-string-face ((t (:slant oblique :foreground "#C2C2C2"))))
 '(font-lock-type-face ((t (:underline (:color foreground-color :style line) :foreground "#D9D9D9"))))
 '(font-lock-variable-name-face ((t (:foreground "#F9F9F9"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#E8E8E8"))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#F6F6F6"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#E8E8E8"))))
 '(fringe ((t (:foreground "#080808" :background "#161616"))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color "Black" :style nil) :foreground "gray60" :background "black"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "yellow" :background "Black" :inherit nil))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:slant italic :box (:line-width -3 :color "black" :style nil) :foreground "gray60" :background "Black"))))
 '(isearch ((t (:background "#F0F0F0" :weight bold :foreground "#161616"))))
 '(isearch-fail ((t (:foreground "#F6F6F6" :background "#616161"))))
 '(lazy-highlight ((t (:background "#9D9D9D" :weight bold :foreground "#161616"))))
 '(match ((t (:weight bold :foreground "#E8E8E8" :background "#0E0E0E"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'panda)
